### PR TITLE
[JENKINS-41907] obtain IdP Metadata from URL

### PR DESCRIPTION
**Pull request by kuisathaverat**
[JENKINS-41907](https://issues.jenkins-ci.org/browse/JENKINS-41907) - Evaluate to obtain IdP Metadata from URL

This feature resolves these issues
[JENKINS-48031](https://issues.jenkins-ci.org/browse/JENKINS-48031) - SAML plugin does not accept xml tag in Idp metadata (azure)
[JENKINS-47880](https://issues.jenkins-ci.org/browse/JENKINS-47880) - Navigating to /securityRealm/finishLogin manually shows an odd error
[JENKINS-44992](https://issues.jenkins-ci.org/browse/JENKINS-44992) - SamlException after metadata update

Other minor issues fixed
[JENKINS-46098](https://issues.jenkins-ci.org/browse/JENKINS-46098) -SAMLException on login Identity provider has no single sign on service available
[JENKINS-48030](https://issues.jenkins-ci.org/browse/JENKINS-48030) - SAML Azure AD exception
[JENKINS-46063](https://issues.jenkins-ci.org/browse/JENKINS-46063) - do not allow blank passwords

Acceptance test harness
https://github.com/jenkinsci/acceptance-test-harness/pull/391

@reviewbybees

### CODE REVIEW

**Comment by walliski** [comment]
Hey

What is the progress of this? Really looking forward to it!

//Walliski

**Comment by kuisathaverat** [comment]
@walliski it is ready, if you want to test you can download the binary from https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsaml-plugin/detail/PR-39/7/artifacts

**Comment by walliski** [comment]
@kuisathaverat Tried using this one, with some problems O:)

Probably not (?) the correct place, but here goes:

It is writing `Could not construct the directory structure for SP metadata /var/jenkins_home/saml-sp-metadata.xml` to the console now and then, even though the file exists and it writes data to it (according to logs writing data to it before attempting to create directory?).

When trying to log in without private browsing i get this error: `org.pac4j.saml.exceptions.SAMLException: Authentication issue instant is too old or in the future`, followed by `org.pac4j.saml.exceptions.SAMLException: No valid subject assertion found in response`. Clock is synced on the server.

Any ideas?

**Comment by kuisathaverat** [comment]
>Could not construct the directory structure for SP metadata /var/jenkins_home/saml-sp-metadata.xml

this is a warning from pac4j library, it does not matter, the file is created.

>When trying to log in without private browsing i get this error: org.pac4j.saml.exceptions.SAMLException: Authentication issue instant is too old or in the future, followed by org.pac4j.saml.exceptions.SAMLException: No valid subject assertion found in response when getting redirected to finishLogin. Clock is synced on the server.
Logging in with private browsing works though. Same message about the directory structure, but else logs me in.

probably if you cleanup the cookies it will work, if it happens again you have to check these issue comment https://issues.jenkins-ci.org/browse/JENKINS-48030?focusedCommentId=321796&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-321796 to adjust the session lifetime

**Comment by walliski** [comment]
Thanks, I'll try that!

**Pull request merged**
