### PR TITLE
[JENKINS-55175] - Use Mockito from Plugin POM to support testing with Java 11

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-55175

Requires https://github.com/jenkinsci/plugin-pom/pull/141 to be released first

@jenkinsci/java11-support

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Findbugs, hmm... But it should not be related to the Mockito update itself

```
[INFO] org.jenkinsci.plugins.saml.BundleKeyStore.saveKeyStore(File, KeyStore, String) may fail to clean up java.io.OutputStream [org.jenkinsci.plugins.saml.BundleKeyStore, org.jenkinsci.plugins.saml.BundleKeyStore, org.jenkinsci.plugins.saml.BundleKeyStore, org.jenkinsci.plugins.saml.BundleKeyStore, org.jenkinsci.plugins.saml.BundleKeyStore] Obligation to clean up resource created at BundleKeyStore.java:[line 184] is not dischargedPath continues at BundleKeyStore.java:[line 186]Path continues at BundleKeyStore.java:[line 188]Path continues at BundleKeyStore.java:[line 189]Path continues at BundleKeyStore.java:[line 190] OBL_UNSATISFIED_OBLIGATION

[INFO] The field org.jenkinsci.plugins.saml.SamlAuthenticationToken.session is transient but isn't set by deserialization [org.jenkinsci.plugins.saml.SamlAuthenticationToken] In SamlAuthenticationToken.java SE_TRANSIENT_FIELD_NOT_RESTORED

[INFO] Nullcheck of in at line 30 of value previously dereferenced in org.jenkinsci.plugins.saml.SamlValidateIdPMetadata.process() [org.jenkinsci.plugins.saml.SamlValidateIdPMetadata, org.jenkinsci.plugins.saml.SamlValidateIdPMetadata] At SamlValidateIdPMetadata.java:[line 30]Redundant null check at SamlValidateIdPMetadata.java:[line 38] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
```

**Comment by kuisathaverat** [comment]
super, findbugs fails only on some OS+JDK 😲

**Comment by kuisathaverat** [comment]
I filed [JENKINS-55205](https://issues.jenkins-ci.org/browse/JENKINS-55205) to review it.

**Comment by oleg-nenashev** [comment]
@kuisathaverat maybe you want to update to the final release of Plugin POM at least.

**Comment by oleg-nenashev** [comment]
I recommend to wait till 3.31 with https://github.com/jenkinsci/maven-hpi-plugin/pull/88 though

**Comment by kuisathaverat** [comment]
sure, I will make it in the same JENKINS-55205 PR

**Pull request merged**
