### PR TITLE
Document that a system property is required for ADFS

### PR DESCRIPTION
**Pull request by Vlatombe**
Seems like https://github.com/jenkinsci/saml-plugin/pull/89 has changed some behaviour w.r.t Base64 encoding, and ADFS doesn't like seeing line breaks and complains.

/cc @schottsfired

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Appropriate autotests or explanation to why this change has no tests

### CODE REVIEW

**Review by schottsfired — APPROVED** [review]
[SANCTUARIO-482](https://issues.apache.org/jira/browse/SANTUARIO-482) for additional context.

I also suspect [JENKINS-63703](https://issues.jenkins-ci.org/browse/JENKINS-63703) is related, but not sure.

**Comment by kuisathaverat** [comment]
> [SANCTUARIO-482](https://issues.apache.org/jira/browse/SANTUARIO-482) for additional context.
> 
> I also suspect [JENKINS-63703](https://issues.jenkins-ci.org/browse/JENKINS-63703) is related, but not sure.

The Problem that @Vlatombe is talking about is related to the request to the ADFS (Jenkins->ADFS), [JENKINS-63703](https://issues.jenkins-ci.org/browse/JENKINS-63703) is related to the SAMLResponse signature, I am not sure is the same Jenkins accepts linebreaks in the signature.

**Comment by kuisathaverat** [comment]
@Vlatombe I guess you have tested it, isn't it?

**Review by kuisathaverat — APPROVED** [review]

**Comment by Vlatombe** [comment]
Sure, this was based on a customer issue

**Pull request merged**
