### PR TITLE
feat: support random generated relayState parameter

### PR DESCRIPTION
**Pull request by kuisathaverat**
It adds support to use a random value for the relayState SAML parameter

### CODE REVIEW

**Comment by daniel-beck** [comment]
What's the motivation for this?

Context: https://github.com/jenkinsci/jenkins/pull/10630, I'm looking into `RelayState` to hold the redirect URL instead of a session attribute.

**Comment by kuisathaverat** [comment]
@daniel-beck the answer is in the PR, check the help of the new option.

**Comment by daniel-beck** [comment]
@kuisathaverat Thanks, I understand what it does, just not why it does that.

FWIW I've since found the false-positive report that motivated this change.

Would you consider this an important feature to retain, or could it easily be removed in favor of other relay state uses?

**Comment by daniel-beck** [comment]
> What is the motivation for removing it?

https://github.com/jenkinsci/jenkins/pull/10630 would prevent the redirect from being available in the session in `doFinishLogin`, so my thought was to accomplish this via relay state after a bit of googling. So far I struggle to accomplish that though, so TBD whether that's actually a viable approach. If you have an idea how this could be done without having the old session available in `doFinishLogin` (relay state or not), please let me know!

**Comment by kuisathaverat** [comment]
I saw issues with SameSite in the past https://github.com/jenkinsci/saml-plugin/pull/437#issuecomment-2344744303

**Comment by daniel-beck** [comment]
Current WIP effort in https://github.com/jenkinsci/saml-plugin/pull/514.

**Pull request merged**
